apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipeline-service-account-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 0.5.1, pipelines.kubeflow.org/pipeline_compilation_time: '2020-06-21T17:31:07.754531',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "The pipeline shows how
      to set the max number of parallel pods in a pipeline.", "name": "Pipeline service
      account"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 0.5.1}
spec:
  entrypoint: pipeline-service-account
  templates:
  - name: pipeline-service-account
    dag:
      tasks:
      - {name: print, template: print}
      - {name: print-2, template: print-2}
  - name: print
    container:
      command: [echo, 'hey, what are you up to?']
      image: alpine:3.6
    metadata:
      labels: {pipelines.kubeflow.org/pipeline-sdk-type: kfp}
  - name: print-2
    container:
      command: [echo, train my model.]
      image: alpine:3.6
    metadata:
      labels: {pipelines.kubeflow.org/pipeline-sdk-type: kfp}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
  parallelism: 1
