apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: save-most-frequent-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 0.5.1, pipelines.kubeflow.org/pipeline_compilation_time: '2020-06-21T14:35:13.603187',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Get Most Frequent Word
      and Save to GCS", "inputs": [{"name": "message", "type": "String"}], "name":
      "Save Most Frequent"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 0.5.1}
spec:
  entrypoint: save-most-frequent
  templates:
  - name: get-frequent
    container:
      args: ['python -c "from collections import Counter; words = Counter(''{{inputs.parameters.message}}''.split());
          print(max(words, key=words.get))" | tee /tmp/message.txt']
      command: [sh, -c]
      image: python:3.5-jessie
    inputs:
      parameters:
      - {name: message}
    outputs:
      artifacts:
      - {name: get-frequent-word, path: /tmp/message.txt}
    metadata:
      labels: {pipelines.kubeflow.org/pipeline-sdk-type: kfp}
  - name: save-most-frequent
    inputs:
      parameters:
      - {name: message}
    dag:
      tasks:
      - name: get-frequent
        template: get-frequent
        arguments:
          parameters:
          - {name: message, value: '{{inputs.parameters.message}}'}
  arguments:
    parameters:
    - {name: message}
  serviceAccountName: pipeline-runner
  imagePullSecrets:
  - {name: secretA}
