apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipeline-with-sidecar-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 0.5.1, pipelines.kubeflow.org/pipeline_compilation_time: '2020-06-21T18:17:55.503060',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A pipeline that demonstrates
      how to add a sidecar to an operation.", "inputs": [{"default": "30", "name":
      "sleep_sec", "optional": true, "type": "Integer"}], "name": "pipeline_with_sidecar"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 0.5.1}
spec:
  entrypoint: pipeline-with-sidecar
  templates:
  - name: download
    container:
      args: ['sleep {{inputs.parameters.sleep_sec}}; wget localhost:5678 -O /tmp/results.txt']
      command: [sh, -c]
      image: busybox:latest
    inputs:
      parameters:
      - {name: sleep_sec}
    outputs:
      parameters:
      - name: download-downloaded
        valueFrom: {path: /tmp/results.txt}
      artifacts:
      - {name: download-downloaded, path: /tmp/results.txt}
    metadata:
      labels: {pipelines.kubeflow.org/pipeline-sdk-type: kfp}
    sidecars:
    - args: [-text="hello world"]
      image: hashicorp/http-echo:latest
      name: echo
  - name: echo
    container:
      args: ['echo {{inputs.parameters.download-downloaded}}']
      command: [sh, -c]
      image: library/bash
    inputs:
      parameters:
      - {name: download-downloaded}
    metadata:
      labels: {pipelines.kubeflow.org/pipeline-sdk-type: kfp}
  - name: pipeline-with-sidecar
    inputs:
      parameters:
      - {name: sleep_sec}
    dag:
      tasks:
      - name: download
        template: download
        arguments:
          parameters:
          - {name: sleep_sec, value: '{{inputs.parameters.sleep_sec}}'}
      - name: echo
        template: echo
        dependencies: [download]
        arguments:
          parameters:
          - {name: download-downloaded, value: '{{tasks.download.outputs.parameters.download-downloaded}}'}
  arguments:
    parameters:
    - {name: sleep_sec, value: '30'}
  serviceAccountName: pipeline-runner
